apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /Users/z.kazuki.tanaka/.asdf/installs/kompose/1.26.1/bin/kompose convert -o ./k8s/api -f src/docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /Users/z.kazuki.tanaka/.asdf/installs/kompose/1.26.1/bin/kompose convert -o ./k8s/api -f src/docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
        - image: golang:latest
          name: app
          ports:
            - containerPort: 8080
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /home
              name: app-claim0
      restartPolicy: Always
      volumes:
        - name: app-claim0
          persistentVolumeClaim:
            claimName: app-claim0
status: {}
