apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /Users/z.kazuki.tanaka/.asdf/installs/kompose/1.26.1/bin/kompose convert -o ./k8s/api -f src/docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  ports:
    - name: "13306"
      port: 13306
      targetPort: 3306
  selector:
    io.kompose.service: mysql
status:
  loadBalancer: {}
